site_name: LLM Chat Documentation
site_description: LLMチャットボットのドキュメント
site_author: Team

theme:
  name: material
  language: ja
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.code.copy

nav:
  - ホーム:
    - プロジェクト概要: index.md
    - 導入ガイド: getting_started.md
    - GitHub Pages設定: github_pages_setup.md
  - 仕様書:
    - プロンプトエディタ: specifications/prompt_editor_spec.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - footnotes
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search:
      lang: ja

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/noppomario/llm-chat